import Head from 'next/head'
import styles from '../styles/Home.module.css'
import carData from '../data/carData.json'

import Link from 'next/link'
import { motion } from 'framer'
import { v4 as uuid } from 'uuid'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.browse}>
        <h1>Browse Cars</h1>
        <div className={styles.cars}>
          {carData.map((car, index) => {

            return (
              <Link key={uuid()} href={ `/car/${index}` }>
                <motion.a whileHover={{scale: 1.1}} className={styles.car}>
                  <img src={car.img} alt="car" />
                  <h2>{car.name}</h2>
                </motion.a>
              </Link>
            )
          })}
        </div>
      </main>
    </div>
  )
}
